version: '2'
services:
    jhapp-app:
        image: jhapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhapp-mysql:3306/jhapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhapp-mysql:
        extends:
            file: mysql.yml
            service: jhapp-mysql
